version: '3.8'

services:
  app:
    image: node:16 
    container_name: node-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: mydb
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    command: "npm run start"

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"

volumes:
  db-data:
    name: ssss_ss_S
